### ISSUE TITLE
2.x Compatible

### ISSUE THREAD

**Issue by BuiltByLou** [vln104/MauticSpamAssassinChecker#1]
Hi,
installed the plugin in mautic 2.x and didnt find her anywhere.

Is it compatible?

**Comment by vln104** [comment]
Hi,

Unfortunately I haven't been keeping this up to date. If you need to see the spam score, I would recommend going to http://spamcheck.postmarkapp.com and paste the contents of your email including header. The plugin does just that using an API.

Linh

**Comment by BuiltByLou** [comment]
Hi,

Ok thanks for your reply 👍
